# Specify disk image to work on

DISK_IMAGE = "output/OxizeOS.hdd"

# Setup the disk

DISK_INIT(format="RAW", size="1G")

MKPART(index=1, label="EFI System Partition", code="EF00", start=2048, sectors=524288, letter="W:")
MKPART(index=2, label="OxizeOS System Partition", code="0700", start=528384, sectors=1566687, letter="C:")

MKFS(part=1, label="EFI SYSPART")
MKFS(part=2, label="OS SYSPART")

# Setup ESP

MKDIR(path="W:\EFI")
MKDIR(path="W:\EFI\BOOT")
MKDIR(path="W:\EFI\OxizeOS")

COPY(src="resources/descriptors/EFI_SYSPART.CONF", dst="W:\VOLID.CONF")
COPY(src="output/BootMgr.exe", dst="W:\EFI\BOOT\BOOTX64.EFI")
COPY(src="output/syskrnl64.exe", dst="W:\EFI\OxizeOS\syskrnl64.exe")

# Setup OS Partition

MKDIR(path="C:\OxizeOS")
MKDIR(path="C:\OxizeOS\System")

COPY(src="resources/descriptors/OS_SYSPART.CONF", dst="C:\VOLID.CONF")
COPY(src="resources/tests/test.txt", dst="C:\OxizeOS\System\test.txt")