#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-or-later

# Prevent execution when errors appear
set -e

# Vars

OPERATION=$1

VM_NAME="OxizeOS"
DISK_PATH="output/OxizeOS.hdd"

# Functions for VM management

# Deletes the VM

delete_vm() {
    echo "Deleting VM $VM_NAME"
    if VBoxManage list runningvms | grep -q "\"$VM_NAME\""; then
        echo "Powering off VM $VM_NAME"
        VBoxManage controlvm "$VM_NAME" poweroff
        while VBoxManage list runningvms | grep -q "\"$VM_NAME\""; do
            sleep 0.5
        done
    fi
    VBoxManage unregistervm "$VM_NAME" || true
    rm -rf VBoxVM
}

# Creates the VM

create_vm() {
    if [[ ! -f "$DISK_PATH" ]]; then
        echo "Disk image $DISK_PATH Doesn't exist"
        exit 1 
    fi
    echo "Creating new VM $VM_NAME"
    mkdir -p VBoxVM
    echo "" > logfile.log

    VBoxManage createvm --name "$VM_NAME" --basefolder "$(pwd)/VBoxVM"
    VBoxManage registervm "VBoxVM/$VM_NAME/$VM_NAME.vbox"

	VBoxManage modifyvm "$VM_NAME" --chipset ich9 --firmware efi --pae on --longmode on --hpet on
    VBoxManage modifyvm "$VM_NAME" --memory 1024 --acpi on --boot1 disk --nic1 nat
    VBoxManage modifyvm "$VM_NAME" --ostype "Other_64" --cpus 1
    VBoxManage storagectl "$VM_NAME" --name "OxizeOS" --add pcie --controller NVMe --bootable on
    VBoxManage storageattach "$VM_NAME" --storagectl "OxizeOS" --port 0 --device 0 --type hdd --medium "$DISK_PATH" --nonrotational on
    VBoxManage modifyvm "$VM_NAME" --vram 128 --graphicscontroller vmsvga
    VBoxManage modifyvm "$VM_NAME" --ioapic on
}

# Check for explicit options

if [[ "$OPERATION" == "delete" ]]; then
    delete_vm
    exit 0
elif [[ "$OPERATION" == "create" ]]; then
    create_vm
    exit 0
elif [[ "$OPERATION" == "recreate" ]]; then
    delete_vm
    create_vm
    exit 0
elif [[ "$OPERATION" == "qemu" ]]; then
    qemu-system-x86_64 -drive if=none,format=raw,file=$DISK_PATH,id=disk0 \
                       -device ahci,id=ahci \
                       -device ide-hd,bus=ahci.0,drive=disk0 \
                       -drive if=pflash,format=raw,readonly=on,file=lib/EDK2/OVMF/OVMF_CODE.fd \
                       -drive if=pflash,format=raw,file=lib/EDK2/OVMF/OVMF_VARS.fd \
                       -bios lib/EDK2/OVMF/OVMF.fd \
                       -smp 4 -cpu host,x2apic=on,invtsc=on \
                       -enable-kvm \
                       -net none -machine q35,hpet=on -m 1024M -vga std -display sdl \
                       -debugcon file:logfile.log -monitor stdio
    exit 0
fi

# Check if VM is already running, useful for script errors

if VBoxManage list runningvms | grep -q "\"$VM_NAME\""; then
    echo "VM $VM_NAME Is already running"
    read -p "Choose action: [R]Power off the VM and start it again, [K]Kill the VM and exit execution, [E]Exit execution: [E] " choice
    case "$choice" in
        [Rr])
            echo "Restarting VM $VM_NAME"
            VBoxManage controlvm "$VM_NAME" poweroff
            while VBoxManage list runningvms | grep -q "\"$VM_NAME\""; do
                sleep 0.5
            done
            VBoxManage startvm "$VM_NAME" --type separate
            exit 0
            ;;
        [Kk])
            echo "Powering off VM $VM_NAME"
            VBoxManage controlvm "$VM_NAME" poweroff
            exit 0
            ;;
        *)
            echo "Exiting"
            exit 0
            ;;
    esac
fi

# Check if creating a new VM is needed

if VBoxManage list vms | grep -q "\"$VM_NAME\""; then
    echo "VM $VM_NAME Already exists"
else
    create_vm
fi

# Start the VM

echo "Starting $VM_NAME"

VBoxManage startvm "$VM_NAME" --type separate

while ! VBoxManage list runningvms | grep -q "\"$VM_NAME\""; do
    sleep 0.5
done