[GENERAL]

VOLUME_LABEL = "EFI System Partition"
VOLUME_SERIAL_GUID = (GUID){73C23722-42D8-4937-87AB-C3C222D95F7F}
VOLUME_TYPE = "EFI SYSTEM"
VOLUME_TYPE_GUID = (GUID){C12A7328-F81F-11D2-BA4B-00A0C93EC93B}
VOLUME_MEMBERS = "OS:OxizeOS; GROUP:SYSTEM"
VOLUME_FLAGS = "RW;PL=SYSTEM"