[GENERAL]

VOLUME_LABEL = "OxizeOS System Partition"
VOLUME_SERIAL_GUID = (GUID){986A330D-7C1A-4DE4-B519-D4F97A3ED1CE}
VOLUME_TYPE = "OXIZEOS SYSTEM"
VOLUME_TYPE_GUID = (GUID){EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
VOLUME_MEMBERS = "OS:OxizeOS; GROUP:SYSTEM; GROUP:USERS"
VOLUME_FLAGS = "RW;PL=USER"