// SPDX-License-Identifier: GPL-3.0-or-later

#include <stdint.h>
#include <stddef.h>

#pragma once

#define PAGE_ALIGN_UP(addr) (((addr) + 0xFFFULL) & ~(0xFFFULL))
#define PAGE_ALIGN_DOWN(addr) ((addr) & ~(0xFFFULL))

#define BLOCK_COUNT(bytes) (((bytes) + 0xFFFULL) / 0x1000ULL)

#define KIBIBYTE 1024ULL
#define MEBIBYTE KIBIBYTE * KIBIBYTE
#define GIBIBYTE MEBIBYTE * KIBIBYTE

#define SECTOR_SIZE 512ULL

#define MapAddr 0xFFFF800000000000ULL

#define PAGE_SIZE 0x1000ULL
#define BLOCK_SIZE PAGE_SIZE

#define ASMCALL extern "C"
#define PACK __attribute__((packed))
#define FPACK __attribute__((packed, aligned(1)))

#define USERSPACE_VADDR_START 0x0000000000400000ULL // Reserve address space 0-0x3FFFFF for null pointer catching
#define USERSPACE_VADDR_END 0x00007FFFFFFFFFFFULL
#define KERNEL_VADDR_START 0xFFFF800000000000ULL
#define KERNEL_VADDR_END 0xFFFFFFFFFFFFFFFFULL

#define UCHAR_MAX 0xFFU
#define USHORT_MAX 0xFFFFU
#define ULONG_MAX 0xFFFFFFFFUL
#define ULONG64_MAX 0xFFFFFFFFFFFFFFFFULL

#define UINT8_MAX UCHAR_MAX
#define UINT16_MAX USHORT_MAX
#define UINT32_MAX ULONG_MAX
#define UINT64_MAX ULONG64_MAX

#define KERNEL_STACK_SIZE 0x80000ULL // 512KiB kernel stack
#define IST1_STACK_SIZE 0x4000ULL // 16KiB IST1 stack size
#define IST2_STACK_SIZE 0x4000ULL // 16KiB IST2 stack size
#define IST3_STACK_SIZE 0x4000ULL // 16KiB IST3 stack size
#define LP_INTHANDLER_STACK_SIZE 0x4000ULL // 16KiB Interrupt Handler stack size
#define LP_BOOTSTRAP_STACK_SIZE 0x8000ULL // 32KiB LP Bootstrap stack size
#define LP_PRIVILEGE_SWITCH_STACK_SIZE 0x1000ULL // 4KiB LP Ring 3 -> Ring 0 transition stack

#define TOTAL_SUPPORTED_LPs 512
#define TOTAL_GDT_ENTRIES 1029

#define RING0_CODE_SEGMENT_OFFSET 0x08
#define RING0_DATA_SEGMENT_OFFSET 0x10
#define RING3_CODE_SEGMENT_OFFSET 0x18
#define RING3_DATA_SEGMENT_OFFSET 0x20
#define BSP_TASK_SWITCH_SEGMENT_OFFSET 0x28

// Align any value to some power of 2 alignment value
#define ALIGN_UP(value, align) (((value) + (align) - 1) & ~((align) - 1))

enum KRNL_STATUS : uint32_t
{
	KRNL_SUCCESS = 0x00,
	KRNL_INVALID_PARAMETER = 0x01,
	KRNL_UNSUPPORTED = 0x02,
	KRNL_NOT_FOUND = 0x03,
	KRNL_MEMORY_ALLOC_FAILED = 0x04,
	KRNL_STACK_ALLOC_FAILED = 0x05,
	KRNL_CORRUPTED_DATA = 0x06,
	KRNL_OUT_OF_MEMORY = 0x501,

	KRNL_API_RMGR_INVALID_TREE_STRUCTURE = 0x100,

	KRNL_ACPI_INVALID_MADT_ENTRY = 0x200,

	KRNL_API_HMGR_INVALID_HANDLE = 0x300,
	KRNL_API_HMGR_INVALID_HANDLE_ID = 0x301,
	KRNL_API_HMGR_INVALID_HANDLE_REF_ID = 0x302,
	KRNL_API_HMGR_OUTDATED_HANDLE = 0x303,
	KRNL_API_HMGR_INVALID_HANDLE_OBJECT = 0x304,
	KRNL_API_HMGR_CLOSED_HANDLE = 0x305,
	KRNL_API_HMGR_CANNOT_DESTROY_HANDLE_WITH_ACTIVE_HANDLES = 0x306,

	KRNL_LCPU_LP_STARTUP_FAILED = 0x400,
	KRNL_LCPU_LP_INIT_FAILED = 0x401,
	KRNL_LCPU_INVALID_LP_EVENT_DATA = 0x402,
	KRNL_LCPU_INVALID_LP_EVENT = 0x403,
};

#define KRNL_ERROR(status) ((status) != KRNL_SUCCESS)