#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# OxizeOS isr source file generation

import sys

if len(sys.argv) < 3:
	print(f"Syntax: {sys.argv[0]} <path to gen_isrs.cpp> <path to gen_isrs.inc>")
	sys.exit(1)

gen_isrs_cpp_path = sys.argv[1]
gen_isrs_asm_path = sys.argv[2]

gen_isrs_cpp = open(gen_isrs_cpp_path, "w")
gen_isrs_asm = open(gen_isrs_asm_path, "w")

# Generate C++ file

# f = gen_isrs_cpp

ist_indices = {
	8: 1, # Double Fault: IST1 stack
	2: 2, # Non-Maskable Interrupt: IST2 stack
	18: 3 # Machine Check Exception: IST3 stack
}

f = gen_isrs_cpp

f.write("// !!! THIS FILE IS AUTO-GENERATED by scripts/gen_isrs.py !!!\n\n")

f.write("#include <main/defs.hpp>\n")
f.write("#include <arch/x86_64/Interrupts/idt.hpp>\n")
f.write("#include <arch/x86_64/Interrupts/gdt.hpp>\n")

for i in range(256):
	f.write(f"ASMCALL void ISR{i}();\n")

f.write("\nvoid ISR_InitializeGates()\n")
f.write("{\n")

for i in range(256):
	ist = ist_indices.get(i, 0)
	f.write(f"\tkrnl::IDT::SetGate({i}, reinterpret_cast<void*>(ISR{i}), GDT_64BIT_RING0_CODESEG, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT, {ist});\n")

f.write("}\n")

f.close()
gen_isrs_cpp.close()

# Generate Assembly file

errcode_isr_indices = [8, 10, 11, 12, 13, 14, 17, 21, 29, 30]

f = gen_isrs_asm

f.write("; !!! THIS FILE IS AUTO-GENERATED by scripts/gen_isrs.py !!!\n\n")

f.write("[bits 64]\n")
f.write("default rel\n\n")
f.write("section .code\n\n")

for i in range(256):
	if i in errcode_isr_indices:
		f.write(f"ISR_ERRCODE {i}\n")
	else:
		f.write(f"ISR_NOERRCODE {i}\n")

f.close()
gen_isrs_asm.close()