# gen_isrs.py

import sys

if len(sys.argv) < 3:
    print(f"Syntax: {sys.argv[0]} <path to gen_isrs.cpp> <path to gen_isrs.inc>")
    sys.exit(1)

gen_isrs_cpp_path = sys.argv[1]
gen_isrs_asm_path = sys.argv[2]

gen_isrs_cpp = open(gen_isrs_cpp_path, "w")
gen_isrs_asm = open(gen_isrs_asm_path, "w")

# Generate C++ file

# f = gen_isrs_cpp

f = gen_isrs_cpp

f.write("// !!! THIS FILE IS AUTO-GENERATED by scripts/gen_isrs.py !!!\n\n")
f.write("#ifndef ASMCALL\n")
f.write("#define ASMCALL extern \"C\"\n")
f.write("#endif\n\n")

for i in range(256):
    f.write(f"ASMCALL void ISR{i}();\n")

f.write("\nvoid ISR_InitializeGates()\n")
f.write("{\n")

for i in range(256):
    f.write(f"\tTskSchl::IDT::IDT::SetGate({i}, reinterpret_cast<void*>(ISR{i}), GDT_64BIT_RING0_CODESEG, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);\n")

f.write("}\n")

f.close()
gen_isrs_cpp.close()

# Generate Assembly file

errcode_isr_indices = [8, 10, 11, 12, 13, 14, 17, 21, 29, 30]

f = gen_isrs_asm

f.write("; !!! THIS FILE IS AUTO-GENERATED by scripts/gen_isrs.py !!!\n\n")
f.write("[bits 64]\n\n")
f.write("section .text\n\n")

for i in range(256):
    if i in errcode_isr_indices:
        f.write(f"ISR_ERRCODE {i}\n")
    else:
        f.write(f"ISR_NOERRCODE {i}\n")

f.close()
gen_isrs_asm.close()